webtalk_init -webtalk_dir C:/MyWork/AFI_Tool/Vivado_Project/Vivado_Project.sim/sim_1/behav/xsim/xsim.dir/top_function_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 27 23:06:50 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ae6bf1bf-b720-43e6-a984-ed48fca05a83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "faf9e46c573942cab3381b16c253e576" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "764" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6980_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2969087272 -regid "" -xml C:/MyWork/AFI_Tool/Vivado_Project/Vivado_Project.sim/sim_1/behav/xsim/xsim.dir/top_function_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/MyWork/AFI_Tool/Vivado_Project/Vivado_Project.sim/sim_1/behav/xsim/xsim.dir/top_function_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/MyWork/AFI_Tool/Vivado_Project/Vivado_Project.sim/sim_1/behav/xsim/xsim.dir/top_function_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
